image: codogo/pipelines-universal:latest

pipelines:
  branches:
    master:
      - step:
          script:
          - yarn install --pure-lockfile
          - yarn run format
          - yarn run build
          - aws s3 sync build s3://freddieridell.com
